linters:
  packages/components/src/**/*.js:
    - prettier --write
    - eslint --fix
    - git add
  packages/mobile-wallet/src/**/*.js:
    - prettier --write
    - eslint --fix
    - git add
  packages/web-wallet/src/**/*.js:
    - prettier --write
    - eslint --fix
    - git add
